### ISSUE TITLE
AIR 18+ - Android does not register device

### ISSUE THREAD

**Issue by jsaade** [Pushwoosh/pushwoosh-adobe-air#6]
I have set all the configuration to the ones provided in the docs.

In the sample in this git, it seems there is something wrong (check line 75 of "TestPushNotifications-app.xml" , the value PACKAGE_NAME should be changed in order to receive the push notifcation).

In my case, the application is not receiving the user token, I checked the device logcat and this is what I got:

`02-13 00:26:39.973 23541 23541 D gcmExtension: GCMExtension.createContext extId: 
02-13 00:26:39.973 23541 23541 D gcmContext: GCMExtensionContext.GCMExtensionContext
02-13 00:26:39.973 23541 23541 D gcmContext: GCMExtensionContext.getFunctions
02-13 00:26:39.983 23541 23541 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String)' on a null object reference
02-13 00:26:39.984 23541 23541 W System.err: 	at com.pushwoosh.nativeExtensions.PushWoosh.onDeviceReady(Unknown Source)
02-13 00:26:39.984 23541 23541 W System.err: 	at com.pushwoosh.nativeExtensions.PushwooshOnDeviceReady.call(Unknown Source)
02-13 00:26:39.984 23541 23541 W System.err: 	at com.adobe.air.Entrypoints.EntryMainWrapper(Native Method)
02-13 00:26:39.984 23541 23541 W System.err: 	at com.adobe.air.Entrypoints.EntryMain(Entrypoints.java:139)`

**Comment by DimanAM** [comment]
Application is not registering because in your case there is no metadata under application tag at all. Did you forget to add [PW_APPID](https://github.com/Pushwoosh/pushwoosh-adobe-air/blob/70b48ec36a0e1131228d0fb726e46ce1ceb01ca6/PushNotificationsSample/src/TestPushNotifications-app.xml#L61) and [PW_PROJECT_ID](https://github.com/Pushwoosh/pushwoosh-adobe-air/blob/70b48ec36a0e1131228d0fb726e46ce1ceb01ca6/PushNotificationsSample/src/TestPushNotifications-app.xml#L62)?

**Comment by jsaade** [comment]
Seems it was an error from my xml descriptor.
